<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([
            ['des' => 'EL ENCANTO', 'coddep' => '1'],
            ['des' => 'LA CHORRERA', 'coddep' => '1'],
            ['des' => 'LA PEDRERA', 'coddep' => '1'],
            ['des' => 'LA VICTORIA', 'coddep' => '1'],
            ['des' => 'LETICIA', 'coddep' => '1'],
            ['des' => 'MIRITI - PARANA', 'coddep' => '1'],
            ['des' => 'PUERTO ALEGRIA', 'coddep' => '1'],
            ['des' => 'PUERTO ARICA', 'coddep' => '1'],
            ['des' => 'PUERTO NARIÑO', 'coddep' => '1'],
            ['des' => 'PUERTO SANTANDER', 'coddep' => '1'],
            ['des' => 'TARAPACA', 'coddep' => '1'],
            ['des' => 'ABEJORRAL', 'coddep' => '2'],
            ['des' => 'ABRIAQUI', 'coddep' => '2'],
            ['des' => 'ALEJANDRIA', 'coddep' => '2'],
            ['des' => 'AMAGA', 'coddep' => '2'],
            ['des' => 'AMALFI', 'coddep' => '2'],
            ['des' => 'ANDES', 'coddep' => '2'],
            ['des' => 'ANGELOPOLIS', 'coddep' => '2'],
            ['des' => 'ANGOSTURA', 'coddep' => '2'],
            ['des' => 'ANORI', 'coddep' => '2'],
            ['des' => 'ANZA', 'coddep' => '2'],
            ['des' => 'APARTADO', 'coddep' => '2'],
            ['des' => 'ARBOLETES', 'coddep' => '2'],
            ['des' => 'ARGELIA', 'coddep' => '2'],
            ['des' => 'ARMENIA', 'coddep' => '2'],
            ['des' => 'BARBOSA', 'coddep' => '2'],
            ['des' => 'BELLO', 'coddep' => '2'],
            ['des' => 'BELMIRA', 'coddep' => '2'],
            ['des' => 'BETANIA', 'coddep' => '2'],
            ['des' => 'BETULIA', 'coddep' => '2'],
            ['des' => 'BRICEÑO', 'coddep' => '2'],
            ['des' => 'BURITICA', 'coddep' => '2'],
            ['des' => 'CACERES', 'coddep' => '2'],
            ['des' => 'CAICEDO', 'coddep' => '2'],
            ['des' => 'CALDAS', 'coddep' => '2'],
            ['des' => 'CAMPAMENTO', 'coddep' => '2'],
            ['des' => 'CAÑASGORDAS', 'coddep' => '2'],
            ['des' => 'CARACOLI', 'coddep' => '2'],
            ['des' => 'CARAMANTA', 'coddep' => '2'],
            ['des' => 'CAREPA', 'coddep' => '2'],
            ['des' => 'CAROLINA', 'coddep' => '2'],
            ['des' => 'CAUCASIA', 'coddep' => '2'],
            ['des' => 'CHIGORODO', 'coddep' => '2'],
            ['des' => 'CISNEROS', 'coddep' => '2'],
            ['des' => 'CIUDAD BOLIVAR', 'coddep' => '2'],
            ['des' => 'COCORNA', 'coddep' => '2'],
            ['des' => 'CONCEPCION', 'coddep' => '2'],
            ['des' => 'CONCORDIA', 'coddep' => '2'],
            ['des' => 'COPACABANA', 'coddep' => '2'],
            ['des' => 'DABEIBA', 'coddep' => '2'],
            ['des' => 'DONMATIAS', 'coddep' => '2'],
            ['des' => 'EBEJICO', 'coddep' => '2'],
            ['des' => 'EL BAGRE', 'coddep' => '2'],
            ['des' => 'EL CARMEN DE VIBORAL', 'coddep' => '2'],
            ['des' => 'EL SANTUARIO', 'coddep' => '2'],
            ['des' => 'ENTRERRIOS', 'coddep' => '2'],
            ['des' => 'ENVIGADO', 'coddep' => '2'],
            ['des' => 'FREDONIA', 'coddep' => '2'],
            ['des' => 'FRONTINO', 'coddep' => '2'],
            ['des' => 'GIRALDO', 'coddep' => '2'],
            ['des' => 'GIRARDOTA', 'coddep' => '2'],
            ['des' => 'GOMEZ PLATA', 'coddep' => '2'],
            ['des' => 'GRANADA', 'coddep' => '2'],
            ['des' => 'GUADALUPE', 'coddep' => '2'],
            ['des' => 'GUARNE', 'coddep' => '2'],
            ['des' => 'GUATAPE', 'coddep' => '2'],
            ['des' => 'HELICONIA', 'coddep' => '2'],
            ['des' => 'HISPANIA', 'coddep' => '2'],
            ['des' => 'ITAGUI', 'coddep' => '2'],
            ['des' => 'ITUANGO', 'coddep' => '2'],
            ['des' => 'JARDIN', 'coddep' => '2'],
            ['des' => 'JERICO', 'coddep' => '2'],
            ['des' => 'LA CEJA', 'coddep' => '2'],
            ['des' => 'LA ESTRELLA', 'coddep' => '2'],
            ['des' => 'LA PINTADA', 'coddep' => '2'],
            ['des' => 'LA UNION', 'coddep' => '2'],
            ['des' => 'LIBORINA', 'coddep' => '2'],
            ['des' => 'MACEO', 'coddep' => '2'],
            ['des' => 'MARINILLA', 'coddep' => '2'],
            ['des' => 'MEDELLIN', 'coddep' => '2'],
            ['des' => 'MONTEBELLO', 'coddep' => '2'],
            ['des' => 'MURINDO', 'coddep' => '2'],
            ['des' => 'MUTATA', 'coddep' => '2'],
            ['des' => 'NARIÑO', 'coddep' => '2'],
            ['des' => 'NECHI', 'coddep' => '2'],
            ['des' => 'NECOCLI', 'coddep' => '2'],
            ['des' => 'OLAYA', 'coddep' => '2'],
            ['des' => 'PEÑOL', 'coddep' => '2'],
            ['des' => 'PEQUE', 'coddep' => '2'],
            ['des' => 'PUEBLORRICO', 'coddep' => '2'],
            ['des' => 'PUERTO BERRIO', 'coddep' => '2'],
            ['des' => 'PUERTO NARE', 'coddep' => '2'],
            ['des' => 'PUERTO TRIUNFO', 'coddep' => '2'],
            ['des' => 'REMEDIOS', 'coddep' => '2'],
            ['des' => 'RETIRO', 'coddep' => '2'],
            ['des' => 'RIONEGRO', 'coddep' => '2'],
            ['des' => 'SABANALARGA', 'coddep' => '2'],
            ['des' => 'SABANETA', 'coddep' => '2'],
            ['des' => 'SALGAR', 'coddep' => '2'],
            ['des' => 'SAN ANDRES DE CUERQUIA', 'coddep' => '2'],
            ['des' => 'SAN CARLOS', 'coddep' => '2'],
            ['des' => 'SAN FRANCISCO', 'coddep' => '2'],
            ['des' => 'SAN JERONIMO', 'coddep' => '2'],
            ['des' => 'SAN JOSE DE LA MONTAÑA', 'coddep' => '2'],
            ['des' => 'SAN JUAN DE URABA', 'coddep' => '2'],
            ['des' => 'SAN LUIS', 'coddep' => '2'],
            ['des' => 'SAN PEDRO DE LOS MILAGROS', 'coddep' => '2'],
            ['des' => 'SAN PEDRO DE URABA', 'coddep' => '2'],
            ['des' => 'SAN RAFAEL', 'coddep' => '2'],
            ['des' => 'SAN ROQUE', 'coddep' => '2'],
            ['des' => 'SAN VICENTE', 'coddep' => '2'],
            ['des' => 'SANTA BARBARA', 'coddep' => '2'],
            ['des' => 'SANTA ROSA DE OSOS', 'coddep' => '2'],
            ['des' => 'SANTAFE DE ANTIOQUIA', 'coddep' => '2'],
            ['des' => 'SANTO DOMINGO', 'coddep' => '2'],
            ['des' => 'SEGOVIA', 'coddep' => '2'],
            ['des' => 'SONSON', 'coddep' => '2'],
            ['des' => 'SOPETRAN', 'coddep' => '2'],
            ['des' => 'TAMESIS', 'coddep' => '2'],
            ['des' => 'TARAZA', 'coddep' => '2'],
            ['des' => 'TARSO', 'coddep' => '2'],
            ['des' => 'TITIRIBI', 'coddep' => '2'],
            ['des' => 'TOLEDO', 'coddep' => '2'],
            ['des' => 'TURBO', 'coddep' => '2'],
            ['des' => 'URAMITA', 'coddep' => '2'],
            ['des' => 'URRAO', 'coddep' => '2'],
            ['des' => 'VALDIVIA', 'coddep' => '2'],
            ['des' => 'VALPARAISO', 'coddep' => '2'],
            ['des' => 'VEGACHI', 'coddep' => '2'],
            ['des' => 'VENECIA', 'coddep' => '2'],
            ['des' => 'VIGIA DEL FUERTE', 'coddep' => '2'],
            ['des' => 'YALI', 'coddep' => '2'],
            ['des' => 'YARUMAL', 'coddep' => '2'],
            ['des' => 'YOLOMBO', 'coddep' => '2'],
            ['des' => 'YONDO', 'coddep' => '2'],
            ['des' => 'ZARAGOZA', 'coddep' => '2'],
            ['des' => 'ARAUCA', 'coddep' => '3'],
            ['des' => 'ARAUQUITA', 'coddep' => '3'],
            ['des' => 'CRAVO NORTE', 'coddep' => '3'],
            ['des' => 'FORTUL', 'coddep' => '3'],
            ['des' => 'PUERTO RONDON', 'coddep' => '3'],
            ['des' => 'SARAVENA', 'coddep' => '3'],
            ['des' => 'TAME', 'coddep' => '3'],
            ['des' => 'BARANOA', 'coddep' => '4'],
            ['des' => 'BARRANQUILLA', 'coddep' => '4'],
            ['des' => 'CAMPO DE LA CRUZ', 'coddep' => '4'],
            ['des' => 'CANDELARIA', 'coddep' => '4'],
            ['des' => 'GALAPA', 'coddep' => '4'],
            ['des' => 'JUAN DE ACOSTA', 'coddep' => '4'],
            ['des' => 'LURUACO', 'coddep' => '4'],
            ['des' => 'MALAMBO', 'coddep' => '4'],
            ['des' => 'MANATI', 'coddep' => '4'],
            ['des' => 'PALMAR DE VARELA', 'coddep' => '4'],
            ['des' => 'PIOJO', 'coddep' => '4'],
            ['des' => 'POLONUEVO', 'coddep' => '4'],
            ['des' => 'PONEDERA', 'coddep' => '4'],
            ['des' => 'PUERTO COLOMBIA', 'coddep' => '4'],
            ['des' => 'REPELON', 'coddep' => '4'],
            ['des' => 'SABANAGRANDE', 'coddep' => '4'],
            ['des' => 'SABANALARGA', 'coddep' => '4'],
            ['des' => 'SANTA LUCIA', 'coddep' => '4'],
            ['des' => 'SANTO TOMAS', 'coddep' => '4'],
            ['des' => 'SOLEDAD', 'coddep' => '4'],
            ['des' => 'SUAN', 'coddep' => '4'],
            ['des' => 'TUBARA', 'coddep' => '4'],
            ['des' => 'USIACURI', 'coddep' => '4'],
            ['des' => 'BOGOTA', 'coddep' => '5'],
            ['des' => 'ACHI', 'coddep' => '6'],
            ['des' => 'ALTOS DEL ROSARIO', 'coddep' => '6'],
            ['des' => 'ARENAL', 'coddep' => '6'],
            ['des' => 'ARJONA', 'coddep' => '6'],
            ['des' => 'ARROYOHONDO', 'coddep' => '6'],
            ['des' => 'BARRANCO DE LOBA', 'coddep' => '6'],
            ['des' => 'CALAMAR', 'coddep' => '6'],
            ['des' => 'CANTAGALLO', 'coddep' => '6'],
            ['des' => 'CARTAGENA', 'coddep' => '6'],
            ['des' => 'CICUCO', 'coddep' => '6'],
            ['des' => 'CLEMENCIA', 'coddep' => '6'],
            ['des' => 'CORDOBA', 'coddep' => '6'],
            ['des' => 'EL CARMEN DE BOLIVAR', 'coddep' => '6'],
            ['des' => 'EL GUAMO', 'coddep' => '6'],
            ['des' => 'EL PEÑON', 'coddep' => '6'],
            ['des' => 'HATILLO DE LOBA', 'coddep' => '6'],
            ['des' => 'MAGANGUE', 'coddep' => '6'],
            ['des' => 'MAHATES', 'coddep' => '6'],
            ['des' => 'MARGARITA', 'coddep' => '6'],
            ['des' => 'MARIA LA BAJA', 'coddep' => '6'],
            ['des' => 'MOMPOS', 'coddep' => '6'],
            ['des' => 'MONTECRISTO', 'coddep' => '6'],
            ['des' => 'MORALES', 'coddep' => '6'],
            ['des' => 'NOROSI', 'coddep' => '6'],
            ['des' => 'PINILLOS', 'coddep' => '6'],
            ['des' => 'REGIDOR', 'coddep' => '6'],
            ['des' => 'RIO VIEJO', 'coddep' => '6'],
            ['des' => 'SAN CRISTOBAL', 'coddep' => '6'],
            ['des' => 'SAN ESTANISLAO', 'coddep' => '6'],
            ['des' => 'SAN FERNANDO', 'coddep' => '6'],
            ['des' => 'SAN JACINTO', 'coddep' => '6'],
            ['des' => 'SAN JACINTO DEL CAUCA', 'coddep' => '6'],
            ['des' => 'SAN JUAN NEPOMUCENO', 'coddep' => '6'],
            ['des' => 'SAN MARTIN DE LOBA', 'coddep' => '6'],
            ['des' => 'SAN PABLO', 'coddep' => '6'],
            ['des' => 'SANTA CATALINA', 'coddep' => '6'],
            ['des' => 'SANTA ROSA', 'coddep' => '6'],
            ['des' => 'SANTA ROSA DEL SUR', 'coddep' => '6'],
            ['des' => 'SIMITI', 'coddep' => '6'],
            ['des' => 'SOPLAVIENTO', 'coddep' => '6'],
            ['des' => 'TALAIGUA NUEVO', 'coddep' => '6'],
            ['des' => 'TIQUISIO', 'coddep' => '6'],
            ['des' => 'TURBACO', 'coddep' => '6'],
            ['des' => 'TURBANA', 'coddep' => '6'],
            ['des' => 'VILLANUEVA', 'coddep' => '6'],
            ['des' => 'ZAMBRANO', 'coddep' => '6'],
            ['des' => 'ALMEIDA', 'coddep' => '7'],
            ['des' => 'AQUITANIA', 'coddep' => '7'],
            ['des' => 'ARCABUCO', 'coddep' => '7'],
            ['des' => 'BELEN', 'coddep' => '7'],
            ['des' => 'BERBEO', 'coddep' => '7'],
            ['des' => 'BETEITIVA', 'coddep' => '7'],
            ['des' => 'BOAVITA', 'coddep' => '7'],
            ['des' => 'BOYACA', 'coddep' => '7'],
            ['des' => 'BRICEÑO', 'coddep' => '7'],
            ['des' => 'BUENAVISTA', 'coddep' => '7'],
            ['des' => 'BUSBANZA', 'coddep' => '7'],
            ['des' => 'CALDAS', 'coddep' => '7'],
            ['des' => 'CAMPOHERMOSO', 'coddep' => '7'],
            ['des' => 'CERINZA', 'coddep' => '7'],
            ['des' => 'CHINAVITA', 'coddep' => '7'],
            ['des' => 'CHIQUINQUIRA', 'coddep' => '7'],
            ['des' => 'CHIQUIZA', 'coddep' => '7'],
            ['des' => 'CHISCAS', 'coddep' => '7'],
            ['des' => 'CHITA', 'coddep' => '7'],
            ['des' => 'CHITARAQUE', 'coddep' => '7'],
            ['des' => 'CHIVATA', 'coddep' => '7'],
            ['des' => 'CHIVOR', 'coddep' => '7'],
            ['des' => 'CIENEGA', 'coddep' => '7'],
            ['des' => 'COMBITA', 'coddep' => '7'],
            ['des' => 'COPER', 'coddep' => '7'],
            ['des' => 'CORRALES', 'coddep' => '7'],
            ['des' => 'COVARACHIA', 'coddep' => '7'],
            ['des' => 'CUBARA', 'coddep' => '7'],
            ['des' => 'CUCAITA', 'coddep' => '7'],
            ['des' => 'CUITIVA', 'coddep' => '7'],
            ['des' => 'DUITAMA', 'coddep' => '7'],
            ['des' => 'EL COCUY', 'coddep' => '7'],
            ['des' => 'EL ESPINO', 'coddep' => '7'],
            ['des' => 'FIRAVITOBA', 'coddep' => '7'],
            ['des' => 'FLORESTA', 'coddep' => '7'],
            ['des' => 'GACHANTIVA', 'coddep' => '7'],
            ['des' => 'GAMEZA', 'coddep' => '7'],
            ['des' => 'GARAGOA', 'coddep' => '7'],
            ['des' => 'GUACAMAYAS', 'coddep' => '7'],
            ['des' => 'GUATEQUE', 'coddep' => '7'],
            ['des' => 'GUAYATA', 'coddep' => '7'],
            ['des' => 'GÜICAN', 'coddep' => '7'],
            ['des' => 'IZA', 'coddep' => '7'],
            ['des' => 'JENESANO', 'coddep' => '7'],
            ['des' => 'JERICO', 'coddep' => '7'],
            ['des' => 'LA CAPILLA', 'coddep' => '7'],
            ['des' => 'LA UVITA', 'coddep' => '7'],
            ['des' => 'LA VICTORIA', 'coddep' => '7'],
            ['des' => 'LABRANZAGRANDE', 'coddep' => '7'],
            ['des' => 'MACANAL', 'coddep' => '7'],
            ['des' => 'MARIPI', 'coddep' => '7'],
            ['des' => 'MIRAFLORES', 'coddep' => '7'],
            ['des' => 'MONGUA', 'coddep' => '7'],
            ['des' => 'MONGUI', 'coddep' => '7'],
            ['des' => 'MONIQUIRA', 'coddep' => '7'],
            ['des' => 'MOTAVITA', 'coddep' => '7'],
            ['des' => 'MUZO', 'coddep' => '7'],
            ['des' => 'NOBSA', 'coddep' => '7'],
            ['des' => 'NUEVO COLON', 'coddep' => '7'],
            ['des' => 'OICATA', 'coddep' => '7'],
            ['des' => 'OTANCHE', 'coddep' => '7'],
            ['des' => 'PACHAVITA', 'coddep' => '7'],
            ['des' => 'PAEZ', 'coddep' => '7'],
            ['des' => 'PAIPA', 'coddep' => '7'],
            ['des' => 'PAJARITO', 'coddep' => '7'],
            ['des' => 'PANQUEBA', 'coddep' => '7'],
            ['des' => 'PAUNA', 'coddep' => '7'],
            ['des' => 'PAYA', 'coddep' => '7'],
            ['des' => 'PAZ DE RIO', 'coddep' => '7'],
            ['des' => 'PESCA', 'coddep' => '7'],
            ['des' => 'PISBA', 'coddep' => '7'],
            ['des' => 'PUERTO BOYACA', 'coddep' => '7'],
            ['des' => 'QUIPAMA', 'coddep' => '7'],
            ['des' => 'RAMIRIQUI', 'coddep' => '7'],
            ['des' => 'RAQUIRA', 'coddep' => '7'],
            ['des' => 'RONDON', 'coddep' => '7'],
            ['des' => 'SABOYA', 'coddep' => '7'],
            ['des' => 'SACHICA', 'coddep' => '7'],
            ['des' => 'SAMACA', 'coddep' => '7'],
            ['des' => 'SAN EDUARDO', 'coddep' => '7'],
            ['des' => 'SAN JOSE DE PARE', 'coddep' => '7'],
            ['des' => 'SAN LUIS DE GACENO', 'coddep' => '7'],
            ['des' => 'SAN MATEO', 'coddep' => '7'],
            ['des' => 'SAN MIGUEL DE SEMA', 'coddep' => '7'],
            ['des' => 'SAN PABLO DE BORBUR', 'coddep' => '7'],
            ['des' => 'SANTA MARIA', 'coddep' => '7'],
            ['des' => 'SANTA ROSA DE VITERBO', 'coddep' => '7'],
            ['des' => 'SANTA SOFIA', 'coddep' => '7'],
            ['des' => 'SANTANA', 'coddep' => '7'],
            ['des' => 'SATIVANORTE', 'coddep' => '7'],
            ['des' => 'SATIVASUR', 'coddep' => '7'],
            ['des' => 'SIACHOQUE', 'coddep' => '7'],
            ['des' => 'SOATA', 'coddep' => '7'],
            ['des' => 'SOCHA', 'coddep' => '7'],
            ['des' => 'SOCOTA', 'coddep' => '7'],
            ['des' => 'SOGAMOSO', 'coddep' => '7'],
            ['des' => 'SOMONDOCO', 'coddep' => '7'],
            ['des' => 'SORA', 'coddep' => '7'],
            ['des' => 'SORACA', 'coddep' => '7'],
            ['des' => 'SOTAQUIRA', 'coddep' => '7'],
            ['des' => 'SUSACON', 'coddep' => '7'],
            ['des' => 'SUTAMARCHAN', 'coddep' => '7'],
            ['des' => 'SUTATENZA', 'coddep' => '7'],
            ['des' => 'TASCO', 'coddep' => '7'],
            ['des' => 'TENZA', 'coddep' => '7'],
            ['des' => 'TIBANA', 'coddep' => '7'],
            ['des' => 'TIBASOSA', 'coddep' => '7'],
            ['des' => 'TINJACA', 'coddep' => '7'],
            ['des' => 'TIPACOQUE', 'coddep' => '7'],
            ['des' => 'TOCA', 'coddep' => '7'],
            ['des' => 'TOGÜI', 'coddep' => '7'],
            ['des' => 'TOPAGA', 'coddep' => '7'],
            ['des' => 'TOTA', 'coddep' => '7'],
            ['des' => 'TUNJA', 'coddep' => '7'],
            ['des' => 'TUNUNGUA', 'coddep' => '7'],
            ['des' => 'TURMEQUE', 'coddep' => '7'],
            ['des' => 'TUTA', 'coddep' => '7'],
            ['des' => 'TUTAZA', 'coddep' => '7'],
            ['des' => 'UMBITA', 'coddep' => '7'],
            ['des' => 'VENTAQUEMADA', 'coddep' => '7'],
            ['des' => 'VILLA DE LEYVA', 'coddep' => '7'],
            ['des' => 'VIRACACHA', 'coddep' => '7'],
            ['des' => 'ZETAQUIRA', 'coddep' => '7'],
            ['des' => 'AGUADAS', 'coddep' => '8'],
            ['des' => 'ANSERMA', 'coddep' => '8'],
            ['des' => 'ARANZAZU', 'coddep' => '8'],
            ['des' => 'BELALCAZAR', 'coddep' => '8'],
            ['des' => 'CHINCHINA', 'coddep' => '8'],
            ['des' => 'FILADELFIA', 'coddep' => '8'],
            ['des' => 'LA DORADA', 'coddep' => '8'],
            ['des' => 'LA MERCED', 'coddep' => '8'],
            ['des' => 'MANIZALES', 'coddep' => '8'],
            ['des' => 'MANZANARES', 'coddep' => '8'],
            ['des' => 'MARMATO', 'coddep' => '8'],
            ['des' => 'MARQUETALIA', 'coddep' => '8'],
            ['des' => 'MARULANDA', 'coddep' => '8'],
            ['des' => 'NEIRA', 'coddep' => '8'],
            ['des' => 'NORCASIA', 'coddep' => '8'],
            ['des' => 'PACORA', 'coddep' => '8'],
            ['des' => 'PALESTINA', 'coddep' => '8'],
            ['des' => 'PENSILVANIA', 'coddep' => '8'],
            ['des' => 'RIOSUCIO', 'coddep' => '8'],
            ['des' => 'RISARALDA', 'coddep' => '8'],
            ['des' => 'SALAMINA', 'coddep' => '8'],
            ['des' => 'SAMANA', 'coddep' => '8'],
            ['des' => 'SAN JOSE', 'coddep' => '8'],
            ['des' => 'SUPIA', 'coddep' => '8'],
            ['des' => 'VICTORIA', 'coddep' => '8'],
            ['des' => 'VILLAMARIA', 'coddep' => '8'],
            ['des' => 'VITERBO', 'coddep' => '8'],
            ['des' => 'ALBANIA', 'coddep' => '9'],
            ['des' => 'BELEN DE LOS ANDAQUIES', 'coddep' => '9'],
            ['des' => 'CARTAGENA DEL CHAIRA', 'coddep' => '9'],
            ['des' => 'CURILLO', 'coddep' => '9'],
            ['des' => 'EL DONCELLO', 'coddep' => '9'],
            ['des' => 'EL PAUJIL', 'coddep' => '9'],
            ['des' => 'FLORENCIA', 'coddep' => '9'],
            ['des' => 'LA MONTAÑITA', 'coddep' => '9'],
            ['des' => 'MILAN', 'coddep' => '9'],
            ['des' => 'MORELIA', 'coddep' => '9'],
            ['des' => 'PUERTO RICO', 'coddep' => '9'],
            ['des' => 'SAN JOSE DEL FRAGUA', 'coddep' => '9'],
            ['des' => 'SAN VICENTE DEL CAGUAN', 'coddep' => '9'],
            ['des' => 'SOLANO', 'coddep' => '9'],
            ['des' => 'SOLITA', 'coddep' => '9'],
            ['des' => 'VALPARAISO', 'coddep' => '9'],
            ['des' => 'AGUAZUL', 'coddep' => '10'],
            ['des' => 'CHAMEZA', 'coddep' => '10'],
            ['des' => 'HATO COROZAL', 'coddep' => '10'],
            ['des' => 'LA SALINA', 'coddep' => '10'],
            ['des' => 'MANI', 'coddep' => '10'],
            ['des' => 'MONTERREY', 'coddep' => '10'],
            ['des' => 'NUNCHIA', 'coddep' => '10'],
            ['des' => 'OROCUE', 'coddep' => '10'],
            ['des' => 'PAZ DE ARIPORO', 'coddep' => '10'],
            ['des' => 'PORE', 'coddep' => '10'],
            ['des' => 'RECETOR', 'coddep' => '10'],
            ['des' => 'SABANALARGA', 'coddep' => '10'],
            ['des' => 'SACAMA', 'coddep' => '10'],
            ['des' => 'SAN LUIS DE PALENQUE', 'coddep' => '10'],
            ['des' => 'TAMARA', 'coddep' => '10'],
            ['des' => 'TAURAMENA', 'coddep' => '10'],
            ['des' => 'TRINIDAD', 'coddep' => '10'],
            ['des' => 'VILLANUEVA', 'coddep' => '10'],
            ['des' => 'YOPAL', 'coddep' => '10'],
            ['des' => 'ALMAGUER', 'coddep' => '11'],
            ['des' => 'ARGELIA', 'coddep' => '11'],
            ['des' => 'BALBOA', 'coddep' => '11'],
            ['des' => 'BOLIVAR', 'coddep' => '11'],
            ['des' => 'BUENOS AIRES', 'coddep' => '11'],
            ['des' => 'CAJIBIO', 'coddep' => '11'],
            ['des' => 'CALDONO', 'coddep' => '11'],
            ['des' => 'CALOTO', 'coddep' => '11'],
            ['des' => 'CORINTO', 'coddep' => '11'],
            ['des' => 'EL TAMBO', 'coddep' => '11'],
            ['des' => 'FLORENCIA', 'coddep' => '11'],
            ['des' => 'GUACHENE', 'coddep' => '11'],
            ['des' => 'GUAPI', 'coddep' => '11'],
            ['des' => 'INZA', 'coddep' => '11'],
            ['des' => 'JAMBALO', 'coddep' => '11'],
            ['des' => 'LA SIERRA', 'coddep' => '11'],
            ['des' => 'LA VEGA', 'coddep' => '11'],
            ['des' => 'LOPEZ', 'coddep' => '11'],
            ['des' => 'MERCADERES', 'coddep' => '11'],
            ['des' => 'MIRANDA', 'coddep' => '11'],
            ['des' => 'MORALES', 'coddep' => '11'],
            ['des' => 'PADILLA', 'coddep' => '11'],
            ['des' => 'PAEZ', 'coddep' => '11'],
            ['des' => 'PATIA', 'coddep' => '11'],
            ['des' => 'PIAMONTE', 'coddep' => '11'],
            ['des' => 'PIENDAMO', 'coddep' => '11'],
            ['des' => 'POPAYAN', 'coddep' => '11'],
            ['des' => 'PUERTO TEJADA', 'coddep' => '11'],
            ['des' => 'PURACE', 'coddep' => '11'],
            ['des' => 'ROSAS', 'coddep' => '11'],
            ['des' => 'SAN SEBASTIAN', 'coddep' => '11'],
            ['des' => 'SANTA ROSA', 'coddep' => '11'],
            ['des' => 'SANTANDER DE QUILICHAO', 'coddep' => '11'],
            ['des' => 'SILVIA', 'coddep' => '11'],
            ['des' => 'SOTARA', 'coddep' => '11'],
            ['des' => 'SUAREZ', 'coddep' => '11'],
            ['des' => 'SUCRE', 'coddep' => '11'],
            ['des' => 'TIMBIO', 'coddep' => '11'],
            ['des' => 'TIMBIQUI', 'coddep' => '11'],
            ['des' => 'TORIBIO', 'coddep' => '11'],
            ['des' => 'TOTORO', 'coddep' => '11'],
            ['des' => 'VILLA RICA', 'coddep' => '11'],
            ['des' => 'AGUACHICA', 'coddep' => '12'],
            ['des' => 'AGUSTIN CODAZZI', 'coddep' => '12'],
            ['des' => 'ASTREA', 'coddep' => '12'],
            ['des' => 'BECERRIL', 'coddep' => '12'],
            ['des' => 'BOSCONIA', 'coddep' => '12'],
            ['des' => 'CHIMICHAGUA', 'coddep' => '12'],
            ['des' => 'CHIRIGUANA', 'coddep' => '12'],
            ['des' => 'CURUMANI', 'coddep' => '12'],
            ['des' => 'EL COPEY', 'coddep' => '12'],
            ['des' => 'EL PASO', 'coddep' => '12'],
            ['des' => 'GAMARRA', 'coddep' => '12'],
            ['des' => 'GONZALEZ', 'coddep' => '12'],
            ['des' => 'LA GLORIA', 'coddep' => '12'],
            ['des' => 'LA JAGUA DE IBIRICO', 'coddep' => '12'],
            ['des' => 'LA PAZ', 'coddep' => '12'],
            ['des' => 'MANAURE', 'coddep' => '12'],
            ['des' => 'PAILITAS', 'coddep' => '12'],
            ['des' => 'PELAYA', 'coddep' => '12'],
            ['des' => 'PUEBLO BELLO', 'coddep' => '12'],
            ['des' => 'RIO DE ORO', 'coddep' => '12'],
            ['des' => 'SAN ALBERTO', 'coddep' => '12'],
            ['des' => 'SAN DIEGO', 'coddep' => '12'],
            ['des' => 'SAN MARTIN', 'coddep' => '12'],
            ['des' => 'TAMALAMEQUE', 'coddep' => '12'],
            ['des' => 'VALLEDUPAR', 'coddep' => '12'],
            ['des' => 'ACANDI', 'coddep' => '13'],
            ['des' => 'ALTO BAUDO', 'coddep' => '13'],
            ['des' => 'ATRATO', 'coddep' => '13'],
            ['des' => 'BAGADO', 'coddep' => '13'],
            ['des' => 'BAHIA SOLANO', 'coddep' => '13'],
            ['des' => 'BAJO BAUDO', 'coddep' => '13'],
            ['des' => 'BELEN DE BAJIRA', 'coddep' => '13'],
            ['des' => 'BOJAYA', 'coddep' => '13'],
            ['des' => 'CARMEN DEL DARIEN', 'coddep' => '13'],
            ['des' => 'CERTEGUI', 'coddep' => '13'],
            ['des' => 'CONDOTO', 'coddep' => '13'],
            ['des' => 'EL CANTON DEL SAN PABLO', 'coddep' => '13'],
            ['des' => 'EL CARMEN DE ATRATO', 'coddep' => '13'],
            ['des' => 'EL LITORAL DEL SAN JUAN', 'coddep' => '13'],
            ['des' => 'ISTMINA', 'coddep' => '13'],
            ['des' => 'JURADO', 'coddep' => '13'],
            ['des' => 'LLORO', 'coddep' => '13'],
            ['des' => 'MEDIO ATRATO', 'coddep' => '13'],
            ['des' => 'MEDIO BAUDO', 'coddep' => '13'],
            ['des' => 'MEDIO SAN JUAN', 'coddep' => '13'],
            ['des' => 'NOVITA', 'coddep' => '13'],
            ['des' => 'NUQUI', 'coddep' => '13'],
            ['des' => 'QUIBDO', 'coddep' => '13'],
            ['des' => 'RIO IRO', 'coddep' => '13'],
            ['des' => 'RIO QUITO', 'coddep' => '13'],
            ['des' => 'RIOSUCIO', 'coddep' => '13'],
            ['des' => 'SAN JOSE DEL PALMAR', 'coddep' => '13'],
            ['des' => 'SIPI', 'coddep' => '13'],
            ['des' => 'TADO', 'coddep' => '13'],
            ['des' => 'UNGUIA', 'coddep' => '13'],
            ['des' => 'UNION PANAMERICANA', 'coddep' => '13'],
            ['des' => 'AYAPEL', 'coddep' => '14'],
            ['des' => 'BUENAVISTA', 'coddep' => '14'],
            ['des' => 'CANALETE', 'coddep' => '14'],
            ['des' => 'CERETE', 'coddep' => '14'],
            ['des' => 'CHIMA', 'coddep' => '14'],
            ['des' => 'CHINU', 'coddep' => '14'],
            ['des' => 'CIENAGA DE ORO', 'coddep' => '14'],
            ['des' => 'COTORRA', 'coddep' => '14'],
            ['des' => 'LA APARTADA', 'coddep' => '14'],
            ['des' => 'LORICA', 'coddep' => '14'],
            ['des' => 'LOS CORDOBAS', 'coddep' => '14'],
            ['des' => 'MOMIL', 'coddep' => '14'],
            ['des' => 'MONTELIBANO', 'coddep' => '14'],
            ['des' => 'MONTERIA', 'coddep' => '14'],
            ['des' => 'MOÑITOS', 'coddep' => '14'],
            ['des' => 'PLANETA RICA', 'coddep' => '14'],
            ['des' => 'PUEBLO NUEVO', 'coddep' => '14'],
            ['des' => 'PUERTO ESCONDIDO', 'coddep' => '14'],
            ['des' => 'PUERTO LIBERTADOR', 'coddep' => '14'],
            ['des' => 'PURISIMA', 'coddep' => '14'],
            ['des' => 'SAHAGUN', 'coddep' => '14'],
            ['des' => 'SAN ANDRES SOTAVENTO', 'coddep' => '14'],
            ['des' => 'SAN ANTERO', 'coddep' => '14'],
            ['des' => 'SAN BERNARDO DEL VIENTO', 'coddep' => '14'],
            ['des' => 'SAN CARLOS', 'coddep' => '14'],
            ['des' => 'SAN JOSE DE URE', 'coddep' => '14'],
            ['des' => 'SAN PELAYO', 'coddep' => '14'],
            ['des' => 'TIERRALTA', 'coddep' => '14'],
            ['des' => 'TUCHIN', 'coddep' => '14'],
            ['des' => 'VALENCIA', 'coddep' => '14'],
            ['des' => 'AGUA DE DIOS', 'coddep' => '15'],
            ['des' => 'ALBAN', 'coddep' => '15'],
            ['des' => 'ANAPOIMA', 'coddep' => '15'],
            ['des' => 'ANOLAIMA', 'coddep' => '15'],
            ['des' => 'APULO', 'coddep' => '15'],
            ['des' => 'ARBELAEZ', 'coddep' => '15'],
            ['des' => 'BELTRAN', 'coddep' => '15'],
            ['des' => 'BITUIMA', 'coddep' => '15'],
            ['des' => 'BOJACA', 'coddep' => '15'],
            ['des' => 'CABRERA', 'coddep' => '15'],
            ['des' => 'CACHIPAY', 'coddep' => '15'],
            ['des' => 'CAJICA', 'coddep' => '15'],
            ['des' => 'CAPARRAPI', 'coddep' => '15'],
            ['des' => 'CAQUEZA', 'coddep' => '15'],
            ['des' => 'CARMEN DE CARUPA', 'coddep' => '15'],
            ['des' => 'CHAGUANI', 'coddep' => '15'],
            ['des' => 'CHIA', 'coddep' => '15'],
            ['des' => 'CHIPAQUE', 'coddep' => '15'],
            ['des' => 'CHOACHI', 'coddep' => '15'],
            ['des' => 'CHOCONTA', 'coddep' => '15'],
            ['des' => 'COGUA', 'coddep' => '15'],
            ['des' => 'COTA', 'coddep' => '15'],
            ['des' => 'CUCUNUBA', 'coddep' => '15'],
            ['des' => 'EL COLEGIO', 'coddep' => '15'],
            ['des' => 'EL PEÑON', 'coddep' => '15'],
            ['des' => 'EL ROSAL', 'coddep' => '15'],
            ['des' => 'FACATATIVA', 'coddep' => '15'],
            ['des' => 'FOMEQUE', 'coddep' => '15'],
            ['des' => 'FOSCA', 'coddep' => '15'],
            ['des' => 'FUNZA', 'coddep' => '15'],
            ['des' => 'FUQUENE', 'coddep' => '15'],
            ['des' => 'FUSAGASUGA', 'coddep' => '15'],
            ['des' => 'GACHALA', 'coddep' => '15'],
            ['des' => 'GACHANCIPA', 'coddep' => '15'],
            ['des' => 'GACHETA', 'coddep' => '15'],
            ['des' => 'GAMA', 'coddep' => '15'],
            ['des' => 'GIRARDOT', 'coddep' => '15'],
            ['des' => 'GRANADA', 'coddep' => '15'],
            ['des' => 'GUACHETA', 'coddep' => '15'],
            ['des' => 'GUADUAS', 'coddep' => '15'],
            ['des' => 'GUASCA', 'coddep' => '15'],
            ['des' => 'GUATAQUI', 'coddep' => '15'],
            ['des' => 'GUATAVITA', 'coddep' => '15'],
            ['des' => 'GUAYABAL DE SIQUIMA', 'coddep' => '15'],
            ['des' => 'GUAYABETAL', 'coddep' => '15'],
            ['des' => 'GUTIERREZ', 'coddep' => '15'],
            ['des' => 'JERUSALEN', 'coddep' => '15'],
            ['des' => 'JUNIN', 'coddep' => '15'],
            ['des' => 'LA CALERA', 'coddep' => '15'],
            ['des' => 'LA MESA', 'coddep' => '15'],
            ['des' => 'LA PALMA', 'coddep' => '15'],
            ['des' => 'LA PEÑA', 'coddep' => '15'],
            ['des' => 'LA VEGA', 'coddep' => '15'],
            ['des' => 'LENGUAZAQUE', 'coddep' => '15'],
            ['des' => 'MACHETA', 'coddep' => '15'],
            ['des' => 'MADRID', 'coddep' => '15'],
            ['des' => 'MANTA', 'coddep' => '15'],
            ['des' => 'MEDINA', 'coddep' => '15'],
            ['des' => 'MOSQUERA', 'coddep' => '15'],
            ['des' => 'NARIÑO', 'coddep' => '15'],
            ['des' => 'NEMOCON', 'coddep' => '15'],
            ['des' => 'NILO', 'coddep' => '15'],
            ['des' => 'NIMAIMA', 'coddep' => '15'],
            ['des' => 'NOCAIMA', 'coddep' => '15'],
            ['des' => 'PACHO', 'coddep' => '15'],
            ['des' => 'PAIME', 'coddep' => '15'],
            ['des' => 'PANDI', 'coddep' => '15'],
            ['des' => 'PARATEBUENO', 'coddep' => '15'],
            ['des' => 'PASCA', 'coddep' => '15'],
            ['des' => 'PUERTO SALGAR', 'coddep' => '15'],
            ['des' => 'PULI', 'coddep' => '15'],
            ['des' => 'QUEBRADANEGRA', 'coddep' => '15'],
            ['des' => 'QUETAME', 'coddep' => '15'],
            ['des' => 'QUIPILE', 'coddep' => '15'],
            ['des' => 'RICAURTE', 'coddep' => '15'],
            ['des' => 'SAN ANTONIO DEL TEQUENDAMA', 'coddep' => '15'],
            ['des' => 'SAN BERNARDO', 'coddep' => '15'],
            ['des' => 'SAN CAYETANO', 'coddep' => '15'],
            ['des' => 'SAN FRANCISCO', 'coddep' => '15'],
            ['des' => 'SAN JUAN DE RIO SECO', 'coddep' => '15'],
            ['des' => 'SASAIMA', 'coddep' => '15'],
            ['des' => 'SESQUILE', 'coddep' => '15'],
            ['des' => 'SIBATE', 'coddep' => '15'],
            ['des' => 'SILVANIA', 'coddep' => '15'],
            ['des' => 'SIMIJACA', 'coddep' => '15'],
            ['des' => 'SOACHA', 'coddep' => '15'],
            ['des' => 'SOPO', 'coddep' => '15'],
            ['des' => 'SUBACHOQUE', 'coddep' => '15'],
            ['des' => 'SUESCA', 'coddep' => '15'],
            ['des' => 'SUPATA', 'coddep' => '15'],
            ['des' => 'SUSA', 'coddep' => '15'],
            ['des' => 'SUTATAUSA', 'coddep' => '15'],
            ['des' => 'TABIO', 'coddep' => '15'],
            ['des' => 'TAUSA', 'coddep' => '15'],
            ['des' => 'TENA', 'coddep' => '15'],
            ['des' => 'TENJO', 'coddep' => '15'],
            ['des' => 'TIBACUY', 'coddep' => '15'],
            ['des' => 'TIBIRITA', 'coddep' => '15'],
            ['des' => 'TOCAIMA', 'coddep' => '15'],
            ['des' => 'TOCANCIPA', 'coddep' => '15'],
            ['des' => 'TOPAIPI', 'coddep' => '15'],
            ['des' => 'UBALA', 'coddep' => '15'],
            ['des' => 'UBAQUE', 'coddep' => '15'],
            ['des' => 'UNE', 'coddep' => '15'],
            ['des' => 'UTICA', 'coddep' => '15'],
            ['des' => 'VENECIA', 'coddep' => '15'],
            ['des' => 'VERGARA', 'coddep' => '15'],
            ['des' => 'VIANI', 'coddep' => '15'],
            ['des' => 'VILLA DE SAN DIEGO DE UBATE', 'coddep' => '15'],
            ['des' => 'VILLAGOMEZ', 'coddep' => '15'],
            ['des' => 'VILLAPINZON', 'coddep' => '15'],
            ['des' => 'VILLETA', 'coddep' => '15'],
            ['des' => 'VIOTA', 'coddep' => '15'],
            ['des' => 'YACOPI', 'coddep' => '15'],
            ['des' => 'ZIPACON', 'coddep' => '15'],
            ['des' => 'ZIPAQUIRA', 'coddep' => '15'],
            ['des' => 'BARRANCO MINAS', 'coddep' => '16'],
            ['des' => 'CACAHUAL', 'coddep' => '16'],
            ['des' => 'INIRIDA', 'coddep' => '16'],
            ['des' => 'LA GUADALUPE', 'coddep' => '16'],
            ['des' => 'MAPIRIPANA', 'coddep' => '16'],
            ['des' => 'MORICHAL', 'coddep' => '16'],
            ['des' => 'PANA PANA', 'coddep' => '16'],
            ['des' => 'PUERTO COLOMBIA', 'coddep' => '16'],
            ['des' => 'SAN FELIPE', 'coddep' => '16'],
            ['des' => 'CALAMAR', 'coddep' => '17'],
            ['des' => 'EL RETORNO', 'coddep' => '17'],
            ['des' => 'MIRAFLORES', 'coddep' => '17'],
            ['des' => 'SAN JOSE DEL GUAVIARE', 'coddep' => '17'],
            ['des' => 'ACEVEDO', 'coddep' => '18'],
            ['des' => 'AGRADO', 'coddep' => '18'],
            ['des' => 'AIPE', 'coddep' => '18'],
            ['des' => 'ALGECIRAS', 'coddep' => '18'],
            ['des' => 'ALTAMIRA', 'coddep' => '18'],
            ['des' => 'BARAYA', 'coddep' => '18'],
            ['des' => 'CAMPOALEGRE', 'coddep' => '18'],
            ['des' => 'COLOMBIA', 'coddep' => '18'],
            ['des' => 'ELIAS', 'coddep' => '18'],
            ['des' => 'GARZON', 'coddep' => '18'],
            ['des' => 'GIGANTE', 'coddep' => '18'],
            ['des' => 'GUADALUPE', 'coddep' => '18'],
            ['des' => 'HOBO', 'coddep' => '18'],
            ['des' => 'IQUIRA', 'coddep' => '18'],
            ['des' => 'ISNOS', 'coddep' => '18'],
            ['des' => 'LA ARGENTINA', 'coddep' => '18'],
            ['des' => 'LA PLATA', 'coddep' => '18'],
            ['des' => 'NATAGA', 'coddep' => '18'],
            ['des' => 'NEIVA', 'coddep' => '18'],
            ['des' => 'OPORAPA', 'coddep' => '18'],
            ['des' => 'PAICOL', 'coddep' => '18'],
            ['des' => 'PALERMO', 'coddep' => '18'],
            ['des' => 'PALESTINA', 'coddep' => '18'],
            ['des' => 'PITAL', 'coddep' => '18'],
            ['des' => 'PITALITO', 'coddep' => '18'],
            ['des' => 'RIVERA', 'coddep' => '18'],
            ['des' => 'SALADOBLANCO', 'coddep' => '18'],
            ['des' => 'SAN AGUSTIN', 'coddep' => '18'],
            ['des' => 'SANTA MARIA', 'coddep' => '18'],
            ['des' => 'SUAZA', 'coddep' => '18'],
            ['des' => 'TARQUI', 'coddep' => '18'],
            ['des' => 'TELLO', 'coddep' => '18'],
            ['des' => 'TERUEL', 'coddep' => '18'],
            ['des' => 'TESALIA', 'coddep' => '18'],
            ['des' => 'TIMANA', 'coddep' => '18'],
            ['des' => 'VILLAVIEJA', 'coddep' => '18'],
            ['des' => 'YAGUARA', 'coddep' => '18'],
            ['des' => 'ALBANIA', 'coddep' => '19'],
            ['des' => 'BARRANCAS', 'coddep' => '19'],
            ['des' => 'DIBULLA', 'coddep' => '19'],
            ['des' => 'DISTRACCION', 'coddep' => '19'],
            ['des' => 'EL MOLINO', 'coddep' => '19'],
            ['des' => 'FONSECA', 'coddep' => '19'],
            ['des' => 'HATONUEVO', 'coddep' => '19'],
            ['des' => 'LA JAGUA DEL PILAR', 'coddep' => '19'],
            ['des' => 'MAICAO', 'coddep' => '19'],
            ['des' => 'MANAURE', 'coddep' => '19'],
            ['des' => 'RIOHACHA', 'coddep' => '19'],
            ['des' => 'SAN JUAN DEL CESAR', 'coddep' => '19'],
            ['des' => 'URIBIA', 'coddep' => '19'],
            ['des' => 'URUMITA', 'coddep' => '19'],
            ['des' => 'VILLANUEVA', 'coddep' => '19'],
            ['des' => 'ALGARROBO', 'coddep' => '20'],
            ['des' => 'ARACATACA', 'coddep' => '20'],
            ['des' => 'ARIGUANI', 'coddep' => '20'],
            ['des' => 'CERRO SAN ANTONIO', 'coddep' => '20'],
            ['des' => 'CHIVOLO', 'coddep' => '20'],
            ['des' => 'CIENAGA', 'coddep' => '20'],
            ['des' => 'CONCORDIA', 'coddep' => '20'],
            ['des' => 'EL BANCO', 'coddep' => '20'],
            ['des' => 'EL PIÑON', 'coddep' => '20'],
            ['des' => 'EL RETEN', 'coddep' => '20'],
            ['des' => 'FUNDACION', 'coddep' => '20'],
            ['des' => 'GUAMAL', 'coddep' => '20'],
            ['des' => 'NUEVA GRANADA', 'coddep' => '20'],
            ['des' => 'PEDRAZA', 'coddep' => '20'],
            ['des' => 'PIJIÑO DEL CARMEN', 'coddep' => '20'],
            ['des' => 'PIVIJAY', 'coddep' => '20'],
            ['des' => 'PLATO', 'coddep' => '20'],
            ['des' => 'PUEBLOVIEJO', 'coddep' => '20'],
            ['des' => 'REMOLINO', 'coddep' => '20'],
            ['des' => 'SABANAS DE SAN ANGEL', 'coddep' => '20'],
            ['des' => 'SALAMINA', 'coddep' => '20'],
            ['des' => 'SAN SEBASTIAN DE BUENAVISTA', 'coddep' => '20'],
            ['des' => 'SAN ZENON', 'coddep' => '20'],
            ['des' => 'SANTA ANA', 'coddep' => '20'],
            ['des' => 'SANTA BARBARA DE PINTO', 'coddep' => '20'],
            ['des' => 'SANTA MARTA', 'coddep' => '20'],
            ['des' => 'SITIONUEVO', 'coddep' => '20'],
            ['des' => 'TENERIFE', 'coddep' => '20'],
            ['des' => 'ZAPAYAN', 'coddep' => '20'],
            ['des' => 'ZONA BANANERA', 'coddep' => '20'],
            ['des' => 'ACACIAS', 'coddep' => '21'],
            ['des' => 'BARRANCA DE UPIA', 'coddep' => '21'],
            ['des' => 'CABUYARO', 'coddep' => '21'],
            ['des' => 'CASTILLA LA NUEVA', 'coddep' => '21'],
            ['des' => 'CUBARRAL', 'coddep' => '21'],
            ['des' => 'CUMARAL', 'coddep' => '21'],
            ['des' => 'EL CALVARIO', 'coddep' => '21'],
            ['des' => 'EL CASTILLO', 'coddep' => '21'],
            ['des' => 'EL DORADO', 'coddep' => '21'],
            ['des' => 'FUENTE DE ORO', 'coddep' => '21'],
            ['des' => 'GRANADA', 'coddep' => '21'],
            ['des' => 'GUAMAL', 'coddep' => '21'],
            ['des' => 'LA MACARENA', 'coddep' => '21'],
            ['des' => 'LEJANIAS', 'coddep' => '21'],
            ['des' => 'MAPIRIPAN', 'coddep' => '21'],
            ['des' => 'MESETAS', 'coddep' => '21'],
            ['des' => 'PUERTO CONCORDIA', 'coddep' => '21'],
            ['des' => 'PUERTO GAITAN', 'coddep' => '21'],
            ['des' => 'PUERTO LLERAS', 'coddep' => '21'],
            ['des' => 'PUERTO LOPEZ', 'coddep' => '21'],
            ['des' => 'PUERTO RICO', 'coddep' => '21'],
            ['des' => 'RESTREPO', 'coddep' => '21'],
            ['des' => 'SAN CARLOS DE GUAROA', 'coddep' => '21'],
            ['des' => 'SAN JUAN DE ARAMA', 'coddep' => '21'],
            ['des' => 'SAN JUANITO', 'coddep' => '21'],
            ['des' => 'SAN MARTIN', 'coddep' => '21'],
            ['des' => 'URIBE', 'coddep' => '21'],
            ['des' => 'VILLAVICENCIO', 'coddep' => '21'],
            ['des' => 'VISTAHERMOSA', 'coddep' => '21'],
            ['des' => 'ALBAN', 'coddep' => '22'],
            ['des' => 'ALDANA', 'coddep' => '22'],
            ['des' => 'ANCUYA', 'coddep' => '22'],
            ['des' => 'ARBOLEDA', 'coddep' => '22'],
            ['des' => 'BARBACOAS', 'coddep' => '22'],
            ['des' => 'BELEN', 'coddep' => '22'],
            ['des' => 'BUESACO', 'coddep' => '22'],
            ['des' => 'CHACHAGÜI', 'coddep' => '22'],
            ['des' => 'COLON', 'coddep' => '22'],
            ['des' => 'CONSACA', 'coddep' => '22'],
            ['des' => 'CONTADERO', 'coddep' => '22'],
            ['des' => 'CORDOBA', 'coddep' => '22'],
            ['des' => 'CUASPUD', 'coddep' => '22'],
            ['des' => 'CUMBAL', 'coddep' => '22'],
            ['des' => 'CUMBITARA', 'coddep' => '22'],
            ['des' => 'EL CHARCO', 'coddep' => '22'],
            ['des' => 'EL PEÑOL', 'coddep' => '22'],
            ['des' => 'EL ROSARIO', 'coddep' => '22'],
            ['des' => 'EL TABLON DE GOMEZ', 'coddep' => '22'],
            ['des' => 'EL TAMBO', 'coddep' => '22'],
            ['des' => 'FRANCISCO PIZARRO', 'coddep' => '22'],
            ['des' => 'FUNES', 'coddep' => '22'],
            ['des' => 'GUACHUCAL', 'coddep' => '22'],
            ['des' => 'GUAITARILLA', 'coddep' => '22'],
            ['des' => 'GUALMATAN', 'coddep' => '22'],
            ['des' => 'ILES', 'coddep' => '22'],
            ['des' => 'IMUES', 'coddep' => '22'],
            ['des' => 'IPIALES', 'coddep' => '22'],
            ['des' => 'LA CRUZ', 'coddep' => '22'],
            ['des' => 'LA FLORIDA', 'coddep' => '22'],
            ['des' => 'LA LLANADA', 'coddep' => '22'],
            ['des' => 'LA TOLA', 'coddep' => '22'],
            ['des' => 'LA UNION', 'coddep' => '22'],
            ['des' => 'LEIVA', 'coddep' => '22'],
            ['des' => 'LINARES', 'coddep' => '22'],
            ['des' => 'LOS ANDES', 'coddep' => '22'],
            ['des' => 'MAGÜI', 'coddep' => '22'],
            ['des' => 'MALLAMA', 'coddep' => '22'],
            ['des' => 'MOSQUERA', 'coddep' => '22'],
            ['des' => 'NARIÑO', 'coddep' => '22'],
            ['des' => 'OLAYA HERRERA', 'coddep' => '22'],
            ['des' => 'OSPINA', 'coddep' => '22'],
            ['des' => 'PASTO', 'coddep' => '22'],
            ['des' => 'POLICARPA', 'coddep' => '22'],
            ['des' => 'POTOSI', 'coddep' => '22'],
            ['des' => 'PROVIDENCIA', 'coddep' => '22'],
            ['des' => 'PUERRES', 'coddep' => '22'],
            ['des' => 'PUPIALES', 'coddep' => '22'],
            ['des' => 'RICAURTE', 'coddep' => '22'],
            ['des' => 'ROBERTO PAYAN', 'coddep' => '22'],
            ['des' => 'SAMANIEGO', 'coddep' => '22'],
            ['des' => 'SAN ANDRES DE TUMACO', 'coddep' => '22'],
            ['des' => 'SAN BERNARDO', 'coddep' => '22'],
            ['des' => 'SAN LORENZO', 'coddep' => '22'],
            ['des' => 'SAN PABLO', 'coddep' => '22'],
            ['des' => 'SAN PEDRO DE CARTAGO', 'coddep' => '22'],
            ['des' => 'SANDONA', 'coddep' => '22'],
            ['des' => 'SANTA BARBARA', 'coddep' => '22'],
            ['des' => 'SANTACRUZ', 'coddep' => '22'],
            ['des' => 'SAPUYES', 'coddep' => '22'],
            ['des' => 'TAMINANGO', 'coddep' => '22'],
            ['des' => 'TANGUA', 'coddep' => '22'],
            ['des' => 'TUQUERRES', 'coddep' => '22'],
            ['des' => 'YACUANQUER', 'coddep' => '22'],
            ['des' => 'ABREGO', 'coddep' => '23'],
            ['des' => 'ARBOLEDAS', 'coddep' => '23'],
            ['des' => 'BOCHALEMA', 'coddep' => '23'],
            ['des' => 'BUCARASICA', 'coddep' => '23'],
            ['des' => 'CACHIRA', 'coddep' => '23'],
            ['des' => 'CACOTA', 'coddep' => '23'],
            ['des' => 'CHINACOTA', 'coddep' => '23'],
            ['des' => 'CHITAGA', 'coddep' => '23'],
            ['des' => 'CONVENCION', 'coddep' => '23'],
            ['des' => 'CUCUTA', 'coddep' => '23'],
            ['des' => 'CUCUTILLA', 'coddep' => '23'],
            ['des' => 'DURANIA', 'coddep' => '23'],
            ['des' => 'EL CARMEN', 'coddep' => '23'],
            ['des' => 'EL TARRA', 'coddep' => '23'],
            ['des' => 'EL ZULIA', 'coddep' => '23'],
            ['des' => 'GRAMALOTE', 'coddep' => '23'],
            ['des' => 'HACARI', 'coddep' => '23'],
            ['des' => 'HERRAN', 'coddep' => '23'],
            ['des' => 'LA ESPERANZA', 'coddep' => '23'],
            ['des' => 'LA PLAYA', 'coddep' => '23'],
            ['des' => 'LABATECA', 'coddep' => '23'],
            ['des' => 'LOS PATIOS', 'coddep' => '23'],
            ['des' => 'LOURDES', 'coddep' => '23'],
            ['des' => 'MUTISCUA', 'coddep' => '23'],
            ['des' => 'OCAÑA', 'coddep' => '23'],
            ['des' => 'PAMPLONA', 'coddep' => '23'],
            ['des' => 'PAMPLONITA', 'coddep' => '23'],
            ['des' => 'PUERTO SANTANDER', 'coddep' => '23'],
            ['des' => 'RAGONVALIA', 'coddep' => '23'],
            ['des' => 'SALAZAR', 'coddep' => '23'],
            ['des' => 'SAN CALIXTO', 'coddep' => '23'],
            ['des' => 'SAN CAYETANO', 'coddep' => '23'],
            ['des' => 'SANTIAGO', 'coddep' => '23'],
            ['des' => 'SARDINATA', 'coddep' => '23'],
            ['des' => 'SILOS', 'coddep' => '23'],
            ['des' => 'TEORAMA', 'coddep' => '23'],
            ['des' => 'TIBU', 'coddep' => '23'],
            ['des' => 'TOLEDO', 'coddep' => '23'],
            ['des' => 'VILLA CARO', 'coddep' => '23'],
            ['des' => 'VILLA DEL ROSARIO', 'coddep' => '23'],
            ['des' => 'COLON', 'coddep' => '24'],
            ['des' => 'MOCOA', 'coddep' => '24'],
            ['des' => 'ORITO', 'coddep' => '24'],
            ['des' => 'PUERTO ASIS', 'coddep' => '24'],
            ['des' => 'PUERTO CAICEDO', 'coddep' => '24'],
            ['des' => 'PUERTO GUZMAN', 'coddep' => '24'],
            ['des' => 'PUERTO LEGUIZAMO', 'coddep' => '24'],
            ['des' => 'SAN FRANCISCO', 'coddep' => '24'],
            ['des' => 'SAN MIGUEL', 'coddep' => '24'],
            ['des' => 'SANTIAGO', 'coddep' => '24'],
            ['des' => 'SIBUNDOY', 'coddep' => '24'],
            ['des' => 'VALLE DEL GUAMUEZ', 'coddep' => '24'],
            ['des' => 'VILLAGARZON', 'coddep' => '24'],
            ['des' => 'ARMENIA', 'coddep' => '25'],
            ['des' => 'BUENAVISTA', 'coddep' => '25'],
            ['des' => 'CALARCA', 'coddep' => '25'],
            ['des' => 'CIRCASIA', 'coddep' => '25'],
            ['des' => 'CORDOBA', 'coddep' => '25'],
            ['des' => 'FILANDIA', 'coddep' => '25'],
            ['des' => 'GENOVA', 'coddep' => '25'],
            ['des' => 'LA TEBAIDA', 'coddep' => '25'],
            ['des' => 'MONTENEGRO', 'coddep' => '25'],
            ['des' => 'PIJAO', 'coddep' => '25'],
            ['des' => 'QUIMBAYA', 'coddep' => '25'],
            ['des' => 'SALENTO', 'coddep' => '25'],
            ['des' => 'APIA', 'coddep' => '26'],
            ['des' => 'BALBOA', 'coddep' => '26'],
            ['des' => 'BELEN DE UMBRIA', 'coddep' => '26'],
            ['des' => 'DOSQUEBRADAS', 'coddep' => '26'],
            ['des' => 'GUATICA', 'coddep' => '26'],
            ['des' => 'LA CELIA', 'coddep' => '26'],
            ['des' => 'LA VIRGINIA', 'coddep' => '26'],
            ['des' => 'MARSELLA', 'coddep' => '26'],
            ['des' => 'MISTRATO', 'coddep' => '26'],
            ['des' => 'PEREIRA', 'coddep' => '26'],
            ['des' => 'PUEBLO RICO', 'coddep' => '26'],
            ['des' => 'QUINCHIA', 'coddep' => '26'],
            ['des' => 'SANTA ROSA DE CABAL', 'coddep' => '26'],
            ['des' => 'SANTUARIO', 'coddep' => '26'],
            ['des' => 'PROVIDENCIA', 'coddep' => '27'],
            ['des' => 'SAN ANDRES', 'coddep' => '27'],
            ['des' => 'AGUADA', 'coddep' => '28'],
            ['des' => 'ALBANIA', 'coddep' => '28'],
            ['des' => 'ARATOCA', 'coddep' => '28'],
            ['des' => 'BARBOSA', 'coddep' => '28'],
            ['des' => 'BARICHARA', 'coddep' => '28'],
            ['des' => 'BARRANCABERMEJA', 'coddep' => '28'],
            ['des' => 'BETULIA', 'coddep' => '28'],
            ['des' => 'BOLIVAR', 'coddep' => '28'],
            ['des' => 'BUCARAMANGA', 'coddep' => '28'],
            ['des' => 'CABRERA', 'coddep' => '28'],
            ['des' => 'CALIFORNIA', 'coddep' => '28'],
            ['des' => 'CAPITANEJO', 'coddep' => '28'],
            ['des' => 'CARCASI', 'coddep' => '28'],
            ['des' => 'CEPITA', 'coddep' => '28'],
            ['des' => 'CERRITO', 'coddep' => '28'],
            ['des' => 'CHARALA', 'coddep' => '28'],
            ['des' => 'CHARTA', 'coddep' => '28'],
            ['des' => 'CHIMA', 'coddep' => '28'],
            ['des' => 'CHIPATA', 'coddep' => '28'],
            ['des' => 'CIMITARRA', 'coddep' => '28'],
            ['des' => 'CONCEPCION', 'coddep' => '28'],
            ['des' => 'CONFINES', 'coddep' => '28'],
            ['des' => 'CONTRATACION', 'coddep' => '28'],
            ['des' => 'COROMORO', 'coddep' => '28'],
            ['des' => 'CURITI', 'coddep' => '28'],
            ['des' => 'EL CARMEN DE CHUCURI', 'coddep' => '28'],
            ['des' => 'EL GUACAMAYO', 'coddep' => '28'],
            ['des' => 'EL PEÑON', 'coddep' => '28'],
            ['des' => 'EL PLAYON', 'coddep' => '28'],
            ['des' => 'ENCINO', 'coddep' => '28'],
            ['des' => 'ENCISO', 'coddep' => '28'],
            ['des' => 'FLORIAN', 'coddep' => '28'],
            ['des' => 'FLORIDABLANCA', 'coddep' => '28'],
            ['des' => 'GALAN', 'coddep' => '28'],
            ['des' => 'GAMBITA', 'coddep' => '28'],
            ['des' => 'GIRON', 'coddep' => '28'],
            ['des' => 'GUACA', 'coddep' => '28'],
            ['des' => 'GUADALUPE', 'coddep' => '28'],
            ['des' => 'GUAPOTA', 'coddep' => '28'],
            ['des' => 'GUAVATA', 'coddep' => '28'],
            ['des' => 'GÜEPSA', 'coddep' => '28'],
            ['des' => 'HATO', 'coddep' => '28'],
            ['des' => 'JESUS MARIA', 'coddep' => '28'],
            ['des' => 'JORDAN', 'coddep' => '28'],
            ['des' => 'LA BELLEZA', 'coddep' => '28'],
            ['des' => 'LA PAZ', 'coddep' => '28'],
            ['des' => 'LANDAZURI', 'coddep' => '28'],
            ['des' => 'LEBRIJA', 'coddep' => '28'],
            ['des' => 'LOS SANTOS', 'coddep' => '28'],
            ['des' => 'MACARAVITA', 'coddep' => '28'],
            ['des' => 'MALAGA', 'coddep' => '28'],
            ['des' => 'MATANZA', 'coddep' => '28'],
            ['des' => 'MOGOTES', 'coddep' => '28'],
            ['des' => 'MOLAGAVITA', 'coddep' => '28'],
            ['des' => 'OCAMONTE', 'coddep' => '28'],
            ['des' => 'OIBA', 'coddep' => '28'],
            ['des' => 'ONZAGA', 'coddep' => '28'],
            ['des' => 'PALMAR', 'coddep' => '28'],
            ['des' => 'PALMAS DEL SOCORRO', 'coddep' => '28'],
            ['des' => 'PARAMO', 'coddep' => '28'],
            ['des' => 'PIEDECUESTA', 'coddep' => '28'],
            ['des' => 'PINCHOTE', 'coddep' => '28'],
            ['des' => 'PUENTE NACIONAL', 'coddep' => '28'],
            ['des' => 'PUERTO PARRA', 'coddep' => '28'],
            ['des' => 'PUERTO WILCHES', 'coddep' => '28'],
            ['des' => 'RIONEGRO', 'coddep' => '28'],
            ['des' => 'SABANA DE TORRES', 'coddep' => '28'],
            ['des' => 'SAN ANDRES', 'coddep' => '28'],
            ['des' => 'SAN BENITO', 'coddep' => '28'],
            ['des' => 'SAN GIL', 'coddep' => '28'],
            ['des' => 'SAN JOAQUIN', 'coddep' => '28'],
            ['des' => 'SAN JOSE DE MIRANDA', 'coddep' => '28'],
            ['des' => 'SAN MIGUEL', 'coddep' => '28'],
            ['des' => 'SAN VICENTE DE CHUCURI', 'coddep' => '28'],
            ['des' => 'SANTA BARBARA', 'coddep' => '28'],
            ['des' => 'SANTA HELENA DEL OPON', 'coddep' => '28'],
            ['des' => 'SIMACOTA', 'coddep' => '28'],
            ['des' => 'SOCORRO', 'coddep' => '28'],
            ['des' => 'SUAITA', 'coddep' => '28'],
            ['des' => 'SUCRE', 'coddep' => '28'],
            ['des' => 'SURATA', 'coddep' => '28'],
            ['des' => 'TONA', 'coddep' => '28'],
            ['des' => 'VALLE DE SAN JOSE', 'coddep' => '28'],
            ['des' => 'VELEZ', 'coddep' => '28'],
            ['des' => 'VETAS', 'coddep' => '28'],
            ['des' => 'VILLANUEVA', 'coddep' => '28'],
            ['des' => 'ZAPATOCA', 'coddep' => '28'],
            ['des' => 'BUENAVISTA', 'coddep' => '29'],
            ['des' => 'CAIMITO', 'coddep' => '29'],
            ['des' => 'CHALAN', 'coddep' => '29'],
            ['des' => 'COLOSO', 'coddep' => '29'],
            ['des' => 'COROZAL', 'coddep' => '29'],
            ['des' => 'COVEÑAS', 'coddep' => '29'],
            ['des' => 'EL ROBLE', 'coddep' => '29'],
            ['des' => 'GALERAS', 'coddep' => '29'],
            ['des' => 'GUARANDA', 'coddep' => '29'],
            ['des' => 'LA UNION', 'coddep' => '29'],
            ['des' => 'LOS PALMITOS', 'coddep' => '29'],
            ['des' => 'MAJAGUAL', 'coddep' => '29'],
            ['des' => 'MORROA', 'coddep' => '29'],
            ['des' => 'OVEJAS', 'coddep' => '29'],
            ['des' => 'PALMITO', 'coddep' => '29'],
            ['des' => 'SAMPUES', 'coddep' => '29'],
            ['des' => 'SAN BENITO ABAD', 'coddep' => '29'],
            ['des' => 'SAN JUAN DE BETULIA', 'coddep' => '29'],
            ['des' => 'SAN LUIS DE SINCE', 'coddep' => '29'],
            ['des' => 'SAN MARCOS', 'coddep' => '29'],
            ['des' => 'SAN ONOFRE', 'coddep' => '29'],
            ['des' => 'SAN PEDRO', 'coddep' => '29'],
            ['des' => 'SANTIAGO DE TOLU', 'coddep' => '29'],
            ['des' => 'SINCELEJO', 'coddep' => '29'],
            ['des' => 'SUCRE', 'coddep' => '29'],
            ['des' => 'TOLU VIEJO', 'coddep' => '29'],
            ['des' => 'ALPUJARRA', 'coddep' => '30'],
            ['des' => 'ALVARADO', 'coddep' => '30'],
            ['des' => 'AMBALEMA', 'coddep' => '30'],
            ['des' => 'ANZOATEGUI', 'coddep' => '30'],
            ['des' => 'ARMERO', 'coddep' => '30'],
            ['des' => 'ATACO', 'coddep' => '30'],
            ['des' => 'CAJAMARCA', 'coddep' => '30'],
            ['des' => 'CARMEN DE APICALA', 'coddep' => '30'],
            ['des' => 'CASABIANCA', 'coddep' => '30'],
            ['des' => 'CHAPARRAL', 'coddep' => '30'],
            ['des' => 'COELLO', 'coddep' => '30'],
            ['des' => 'COYAIMA', 'coddep' => '30'],
            ['des' => 'CUNDAY', 'coddep' => '30'],
            ['des' => 'DOLORES', 'coddep' => '30'],
            ['des' => 'ESPINAL', 'coddep' => '30'],
            ['des' => 'FALAN', 'coddep' => '30'],
            ['des' => 'FLANDES', 'coddep' => '30'],
            ['des' => 'FRESNO', 'coddep' => '30'],
            ['des' => 'GUAMO', 'coddep' => '30'],
            ['des' => 'HERVEO', 'coddep' => '30'],
            ['des' => 'HONDA', 'coddep' => '30'],
            ['des' => 'IBAGUE', 'coddep' => '30'],
            ['des' => 'ICONONZO', 'coddep' => '30'],
            ['des' => 'LERIDA', 'coddep' => '30'],
            ['des' => 'LIBANO', 'coddep' => '30'],
            ['des' => 'MELGAR', 'coddep' => '30'],
            ['des' => 'MURILLO', 'coddep' => '30'],
            ['des' => 'NATAGAIMA', 'coddep' => '30'],
            ['des' => 'ORTEGA', 'coddep' => '30'],
            ['des' => 'PALOCABILDO', 'coddep' => '30'],
            ['des' => 'PIEDRAS', 'coddep' => '30'],
            ['des' => 'PLANADAS', 'coddep' => '30'],
            ['des' => 'PRADO', 'coddep' => '30'],
            ['des' => 'PURIFICACION', 'coddep' => '30'],
            ['des' => 'RIOBLANCO', 'coddep' => '30'],
            ['des' => 'RONCESVALLES', 'coddep' => '30'],
            ['des' => 'ROVIRA', 'coddep' => '30'],
            ['des' => 'SALDAÑA', 'coddep' => '30'],
            ['des' => 'SAN ANTONIO', 'coddep' => '30'],
            ['des' => 'SAN LUIS', 'coddep' => '30'],
            ['des' => 'SAN SEBASTIAN DE MARIQUITA', 'coddep' => '30'],
            ['des' => 'SANTA ISABEL', 'coddep' => '30'],
            ['des' => 'SUAREZ', 'coddep' => '30'],
            ['des' => 'VALLE DE SAN JUAN', 'coddep' => '30'],
            ['des' => 'VENADILLO', 'coddep' => '30'],
            ['des' => 'VILLAHERMOSA', 'coddep' => '30'],
            ['des' => 'VILLARRICA', 'coddep' => '30'],
            ['des' => 'ALCALA', 'coddep' => '31'],
            ['des' => 'ANDALUCIA', 'coddep' => '31'],
            ['des' => 'ANSERMANUEVO', 'coddep' => '31'],
            ['des' => 'ARGELIA', 'coddep' => '31'],
            ['des' => 'BOLIVAR', 'coddep' => '31'],
            ['des' => 'BUENAVENTURA', 'coddep' => '31'],
            ['des' => 'BUGALAGRANDE', 'coddep' => '31'],
            ['des' => 'CAICEDONIA', 'coddep' => '31'],
            ['des' => 'CALI', 'coddep' => '31'],
            ['des' => 'CALIMA', 'coddep' => '31'],
            ['des' => 'CANDELARIA', 'coddep' => '31'],
            ['des' => 'CARTAGO', 'coddep' => '31'],
            ['des' => 'DAGUA', 'coddep' => '31'],
            ['des' => 'EL AGUILA', 'coddep' => '31'],
            ['des' => 'EL CAIRO', 'coddep' => '31'],
            ['des' => 'EL CERRITO', 'coddep' => '31'],
            ['des' => 'EL DOVIO', 'coddep' => '31'],
            ['des' => 'FLORIDA', 'coddep' => '31'],
            ['des' => 'GINEBRA', 'coddep' => '31'],
            ['des' => 'GUACARI', 'coddep' => '31'],
            ['des' => 'GUADALAJARA DE BUGA', 'coddep' => '31'],
            ['des' => 'JAMUNDI', 'coddep' => '31'],
            ['des' => 'LA CUMBRE', 'coddep' => '31'],
            ['des' => 'LA UNION', 'coddep' => '31'],
            ['des' => 'LA VICTORIA', 'coddep' => '31'],
            ['des' => 'OBANDO', 'coddep' => '31'],
            ['des' => 'PALMIRA', 'coddep' => '31'],
            ['des' => 'PRADERA', 'coddep' => '31'],
            ['des' => 'RESTREPO', 'coddep' => '31'],
            ['des' => 'RIOFRIO', 'coddep' => '31'],
            ['des' => 'ROLDANILLO', 'coddep' => '31'],
            ['des' => 'SAN PEDRO', 'coddep' => '31'],
            ['des' => 'SEVILLA', 'coddep' => '31'],
            ['des' => 'TORO', 'coddep' => '31'],
            ['des' => 'TRUJILLO', 'coddep' => '31'],
            ['des' => 'TULUA', 'coddep' => '31'],
            ['des' => 'ULLOA', 'coddep' => '31'],
            ['des' => 'VERSALLES', 'coddep' => '31'],
            ['des' => 'VIJES', 'coddep' => '31'],
            ['des' => 'YOTOCO', 'coddep' => '31'],
            ['des' => 'YUMBO', 'coddep' => '31'],
            ['des' => 'ZARZAL', 'coddep' => '31'],
            ['des' => 'CARURU', 'coddep' => '32'],
            ['des' => 'MITU', 'coddep' => '32'],
            ['des' => 'PACOA', 'coddep' => '32'],
            ['des' => 'PAPUNAUA', 'coddep' => '32'],
            ['des' => 'TARAIRA', 'coddep' => '32'],
            ['des' => 'YAVARATE', 'coddep' => '32'],
            ['des' => 'CUMARIBO', 'coddep' => '33'],
            ['des' => 'LA PRIMAVERA', 'coddep' => '33'],
            ['des' => 'PUERTO CARREÑO', 'coddep' => '33'],
            ['des' => 'SANTA ROSALIA', 'coddep' => '33']
        ]);
    }
}